<a href="https://colab.research.google.com/github/santiagoahl/Data-transformation-and-manipulation/blob/main/shape_and_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
np_array = np.random.randint(1,10,(3,2))
np_array

array([[5, 2],
       [3, 4],
       [8, 4]])

In [3]:
#Evaluate de dimensions of ur NumPy array
np_array.shape

(3, 2)

In [7]:
#Modify de shape of ur NumPy array
np_array.reshape(1,6)

array([[5, 2, 3, 4, 8, 4]])

In [8]:
#Modify de shape of ur NumPy array
np_array.reshape(2,3) #It becomes equal as the begin

array([[5, 2, 3],
       [4, 8, 4]])

In [9]:
np.reshape(np_array,(1,6))

array([[5, 2, 3, 4, 8, 4]])

## Distict languages reshaping

In [12]:
#Original array
np_array

array([[5, 2],
       [3, 4],
       [8, 4]])

In [10]:
#C Language way
np.reshape(np_array, (2,3), 'C')

array([[5, 2, 3],
       [4, 8, 4]])

In [11]:
#Fortran Language way
np.reshape(np_array, (2,3), 'F')

array([[5, 8, 4],
       [3, 2, 4]])

In [13]:
#My Laptop best way
np.reshape(np_array, (2,3), 'A')

array([[5, 2, 3],
       [4, 8, 4]])