<a href="https://colab.research.google.com/github/santiagoahl/Data-transformation-and-manipulation/blob/main/NumPy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4,5,6,7,8,9]
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
#Convert list to numpy array
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(my_array)

numpy.ndarray

# Matrices

In [ ]:
list_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np_matrix = np.array(list_matrix)
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Indexing

In [ ]:
first_element = my_array[0]
second_element = my_array[1]
print(first_element, second_element)

1 2


In [ ]:
my_array[0]+my_array[1]

3

In [ ]:
#Now with matrices 

first_column = np_matrix[0]
first_column

array([1, 2, 3])

In [ ]:
#Acced to matrix element
element = np_matrix[0,1]
element

2

## Slicing

In [ ]:
my_slice = my_array[1:6]
my_slice

array([2, 3, 4, 5, 6])

In [ ]:
inverted_array = my_array[::-1]
inverted_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
from_start_array = my_array[:7]
from_start_array

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
from_specific_value = my_array[2:]
from_specific_value

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#By STEPS
step = int(3)
step_array = my_array[::step]
step_array 

array([1, 4, 7])

In [ ]:
#For matrices
np_matrix[1:]

array([[4, 5, 6],
       [7, 8, 9]])

So we can combine slicing methods in matrices:

In [ ]:
#Slicing columns and rows
np_matrix[1:,:2]

array([[4, 5],
       [7, 8]])