<a href="https://colab.research.google.com/github/santiagoahl/Data-transformation-and-manipulation/blob/main/numpy_data_types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Visualice data types in our NumPy array

In [2]:
array = np.array([1,2,3,4])
array.dtype

dtype('int64')

In [3]:
#Fixing dtype
array = np.array([1,2,3,4], dtype = 'float64')
array.dtype

dtype('float64')

## Cast datatype

In [9]:
array = np.array([1,2,0,4])
array.dtype

dtype('int64')

In [13]:
#To float
float_array = array.astype(np.float64)
float_array

array([1., 2., 0., 4.])

In [10]:
#To bool
bool_array = array.astype(np.bool_)
bool_array #Observe that only 0 is False

array([ True,  True, False,  True])

In [12]:
#To string
string_array = array.astype(np.string_)
string_array

array([b'1', b'2', b'0', b'4'], dtype='|S21')

In [15]:
#String to int
int_array = string_array.astype(np.int8) #Values MUST be integers
int_array

array([1, 2, 0, 4], dtype=int8)