<a href="https://colab.research.google.com/github/santiagoahl/Data-transformation-and-manipulation/blob/main/numPy_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operations in numpy

In [1]:
import numpy as np

In [2]:
my_list = [1,2]
my_list

[1, 2]

In [4]:
#This is a concatenation
2*my_list

[1, 2, 1, 2]

But what if we use numpy?

In [5]:
arr = np.array(my_list)
arr

array([1, 2])

In [6]:
arr2 = arr.copy()

## Operations examples

In [8]:
2*arr2 #It works!!!


array([2, 4])

In [9]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Division
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
#Power
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
matrix = arr.reshape(2,5)
matrix2=matrix.copy()

In [14]:
matrix + matrix2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [16]:
#Matrix product
np.matmul(matrix,matrix2.T)

array([[ 30,  80],
       [ 80, 255]])

In [17]:
matrix @ matrix2.T

array([[ 30,  80],
       [ 80, 255]])

[Click here](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations) for further information.