<a href="https://colab.research.google.com/github/santiagoahl/Data-transformation-and-manipulation/blob/main/building_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Building arrays with numpy
In this notebook, I'm gonna show you how to create the main NumPy array types used in data science.

In [1]:
import numpy as np

In [2]:
#Python code
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

## Numpy proper arrays

In [5]:
#Numpy arange
step = 2
np.arange(0,10,step)

array([0, 2, 4, 6, 8])

In [7]:
#Zeros numpy array
np.zeros(3)
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
#Ones numpy array
np.ones(3)
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Linspace

In [10]:
start = 0
finish = 1
step = 100
np.linspace(start, finish, step)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

# Identity Matrix


In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random array

In [12]:
#Random scalar
np.random.rand() 

0.7388944260510785

In [13]:
#Random vector
np.random.rand(4) 

array([0.16596156, 0.56807437, 0.0846325 , 0.99414385])

In [15]:
#Random matrix
np.random.rand(4,4) 

array([[0.64497994, 0.29160077, 0.24390698, 0.10602003],
       [0.56400625, 0.84085295, 0.22812212, 0.30301103],
       [0.37976837, 0.09497789, 0.18892969, 0.63996873],
       [0.55167713, 0.54540876, 0.85176823, 0.44454668]])

In [16]:
#Random integer
np.random.randint(1,15)

6

In [17]:
#Random integer matrix
np.random.randint(1,100,(10,10))

array([[76, 89, 60, 37, 82, 20, 56, 77, 13, 37],
       [68, 16, 58, 48, 36, 85, 79, 95, 77, 50],
       [97, 18, 27, 71, 89, 77, 95, 68, 51, 31],
       [57, 60, 73, 54, 84, 38,  4, 77, 84, 52],
       [69, 78, 59,  2, 68, 13, 25, 83, 62, 31],
       [97, 62, 25, 63,  7, 26, 34, 72, 13, 54],
       [87, 94, 15, 78, 31, 57,  4, 14,  1, 53],
       [42, 21, 87, 67, 56, 82, 30, 77, 30, 15],
       [69,  8, 55, 29, 56, 49, 93, 37, 80, 34],
       [14, 67, 28, 86, 84, 73, 72, 25, 36,  2]])