<a href="https://colab.research.google.com/github/santiagoahl/Data-transformation-and-manipulation/blob/main/copy_numPy_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Copy function

If certain modifications are made to an extent of an array, the original is modified. To do this, copy is used.

In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
slice = arr[0:6]
slice

array([0, 1, 2, 3, 4, 5])

In [7]:
slice[:] = 0

In [8]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

WARNING: `slice` modified `arr`. That's why we use copy

In [9]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr_copy = arr.copy()

In [15]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

But `arr` is respected

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])