<a href="https://colab.research.google.com/github/santiagoahl/Data-transformation-and-manipulation/blob/main/dimensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dimensions in NumPy

In [2]:
import numpy as np

In [4]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [5]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [8]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
matrix.ndim

[[1 2 3]
 [4 5 6]]


2

In [12]:
tensor = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

## Add or delete dimensions

In [18]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [19]:
#Add 10 dimensions
multi_dimensional_vector = np.array([1,2,3],ndmin=10)
print(multi_dimensional_vector)
multi_dimensional_vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [20]:
#Add one dimension
expand = np.expand_dims(vector,axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [21]:
#Delete dimensions
print(expand, expand.ndim)
reduced_vector = np.squeeze(expand)
print(reduced_vector,reduced_vector.ndim)

[[1 2 3]] 2
[1 2 3] 1
