<a href="https://colab.research.google.com/github/santiagoahl/Data-transformation-and-manipulation/blob/main/main_functions_numPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [11]:
arr = np.random.randint(1,20,10)
arr

array([10,  5, 17,  2,  5, 18,  9, 17, 19, 17])

In [12]:
matrix = arr.reshape(2,5)
matrix

array([[10,  5, 17,  2,  5],
       [18,  9, 17, 19, 17]])

## Max and min values

In [6]:
#Maximal element
arr.max()

18

In [9]:
axis = 0
matrix.max(axis)

array([18, 18, 12, 16, 17])

In [14]:
#Max value index
max_index = arr.argmax()
max_index

8

In [15]:
#Minimal element
matrix.min()

2

In [16]:
#Minimal index
matrix.argmin()

3

## Pick to Pick

In [17]:
#Difference between max and min
arr.ptp()

17

## Statistics

Here is the [complete guide](https://numpy.org/doc/stable/reference/routines.math.html).

In [19]:
arr.sort()

In [20]:
#Percentiles
np.percentile(arr,50)

13.5

In [21]:
#Median
np.median(arr)

13.5

In [22]:
#Mean
np.mean(arr)

11.9

In [24]:
#Standard deviation
np.std(arr)

6.090155991434045

In [25]:
#Variance
np.var(arr)

37.089999999999996

## Concatenate

In [43]:
a = np.array([[1,2],[3,4]])
b=np.array([5,6])
print(a,'\n\n',b)

[[1 2]
 [3 4]] 

 [5 6]


In [44]:
b.ndim

1

In [48]:
b=np.expand_dims(b,axis=0)

In [49]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
np.concatenate((a,b.T),axis=1) #Observe that b.T is the traspose of b

array([[1, 2, 5],
       [3, 4, 6]])

## Mathematical functions

Follow [this link](https://numpy.org/doc/stable/reference/routines.math.html) for further info.