<a href="https://colab.research.google.com/github/santiagoahl/Data-transformation-and-manipulation/blob/main/numPy_conditionals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Coditionals
What if we want to get specific values from an array according with some specific condition? We should use **conditions**.They are very useful in order to implement a filtering process in an array.

In [1]:
import numpy as np

In [11]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [3]:
#Boolean condition that we can use
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
index_condition_1 = arr > 5
index_condition_2 = arr < 9
index_condition

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
arr[(index_condition_1) & (index_condition_2)]

array([6, 7, 8], dtype=int8)

In [9]:
#Assigning from conditions
arr[arr>5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

## Another conditions

In [12]:
#Divisibility
mod_condition = arr%3==0
arr[(mod_condition)]

array([3, 6, 9], dtype=int8)

Else if schema: `np.where(condition, if value, else value)`

In [13]:
np.where(arr%2==1,1,0)

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

We can even use this conditions with lambda functions:


```
arr = np.arange(1,11)

def number_is_even(num):
    return num % 2 == 0


number_is_even(arr)

lambda_func = lambda x: x % 2 == 0

lambda_func(arr)
```

