<a href="https://colab.research.google.com/github/santiagoahl/Data-transformation-and-manipulation/blob/main/shape_and_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
np_array = np.random.randint(1,10,(3,2))
np_array

array([[5, 2],
       [3, 4],
       [8, 4]])

In [3]:
#Evaluate de dimensions of ur NumPy array
np_array.shape

(3, 2)

In [7]:
#Modify de shape of ur NumPy array
np_array.reshape(1,6)

array([[5, 2, 3, 4, 8, 4]])

In [8]:
#Modify de shape of ur NumPy array
np_array.reshape(2,3) #It becomes equal as the begin

array([[5, 2, 3],
       [4, 8, 4]])

In [9]:
np.reshape(np_array,(1,6))

array([[5, 2, 3, 4, 8, 4]])

## Distict languages reshaping

In [12]:
#Original array
np_array

array([[5, 2],
       [3, 4],
       [8, 4]])

In [10]:
#C Language way
np.reshape(np_array, (2,3), 'C')

array([[5, 2, 3],
       [4, 8, 4]])

In [11]:
#Fortran Language way
np.reshape(np_array, (2,3), 'F')

array([[5, 8, 4],
       [3, 2, 4]])

In [13]:
#My Laptop best way
np.reshape(np_array, (2,3), 'A')

array([[5, 2, 3],
       [4, 8, 4]])

## Tensor shaping

In [14]:
my_tensor = np.random.rand(3,3,4,5)
my_tensor

array([[[[0.73397027, 0.49731989, 0.7462874 , 0.86555417, 0.020604  ],
         [0.31133442, 0.54234953, 0.16461562, 0.05614326, 0.19837459],
         [0.41026279, 0.64282115, 0.47350107, 0.44738004, 0.68047045],
         [0.86130166, 0.60354519, 0.14349418, 0.59309441, 0.99886382]],

        [[0.70673355, 0.46865626, 0.88382299, 0.1748958 , 0.88017656],
         [0.18004044, 0.92849139, 0.95306363, 0.37391307, 0.20821127],
         [0.99159752, 0.52794068, 0.29741963, 0.30555868, 0.99740667],
         [0.523868  , 0.75117294, 0.81681613, 0.75104763, 0.54766922]],

        [[0.85147955, 0.3342603 , 0.00993927, 0.65357   , 0.87559192],
         [0.19345966, 0.91163983, 0.28504964, 0.15911462, 0.45599893],
         [0.40756581, 0.14073802, 0.62864973, 0.17331523, 0.22422608],
         [0.34027067, 0.77664346, 0.80074394, 0.44580881, 0.24367465]]],


       [[[0.76327384, 0.27928713, 0.24730828, 0.53082823, 0.00955976],
         [0.27110771, 0.12630316, 0.81213005, 0.49549674, 0.68975051]

In [15]:
np.reshape(my_tensor,(9,20))

array([[0.73397027, 0.49731989, 0.7462874 , 0.86555417, 0.020604  ,
        0.31133442, 0.54234953, 0.16461562, 0.05614326, 0.19837459,
        0.41026279, 0.64282115, 0.47350107, 0.44738004, 0.68047045,
        0.86130166, 0.60354519, 0.14349418, 0.59309441, 0.99886382],
       [0.70673355, 0.46865626, 0.88382299, 0.1748958 , 0.88017656,
        0.18004044, 0.92849139, 0.95306363, 0.37391307, 0.20821127,
        0.99159752, 0.52794068, 0.29741963, 0.30555868, 0.99740667,
        0.523868  , 0.75117294, 0.81681613, 0.75104763, 0.54766922],
       [0.85147955, 0.3342603 , 0.00993927, 0.65357   , 0.87559192,
        0.19345966, 0.91163983, 0.28504964, 0.15911462, 0.45599893,
        0.40756581, 0.14073802, 0.62864973, 0.17331523, 0.22422608,
        0.34027067, 0.77664346, 0.80074394, 0.44580881, 0.24367465],
       [0.76327384, 0.27928713, 0.24730828, 0.53082823, 0.00955976,
        0.27110771, 0.12630316, 0.81213005, 0.49549674, 0.68975051,
        0.55836509, 0.33867304, 0.58272295, 0